### ISSUE TITLE
Not able to nav back from links

### ISSUE THREAD

**Issue by juliaws** [TradeMe/tractor#111]
I am not able to nav back to a step definition after viewing the mock data attached to it.
It looks like it's not passing the correct folder location of the step definition as the parent and sub-parent folder names that the step definition belong to aren't in the url.  

**Steps to replicate:**
1. Nav to a feature
2. Click on any Given step definition
3. Click on the mock data associated with that step definition
4. Click the browser back button

**Expected Result:**
I'm taken back to the step definition page.

**Actual Result:**
Page is white and the url string isn't correct.

Note: This also affects naving back from a step definition to components.

**Comment by phenomnomnominal** [comment]
Fixed by 

https://github.com/phenomnomnominal/tractor-plugin-mock-requests/commit/178982bb7dc2cb463acb09ab57206a9c8f176935
https://github.com/phenomnomnominal/tractor-plugin-page-objects/commit/7c51250bf2f9f5cefa28e6c53a2cfaf191820bc0
https://github.com/phenomnomnominal/tractor-plugin-step-definitions/commit/959210324f0e679aea58caf099e4562b5ccdec13
