### ISSUE TITLE
Parameters at step definition

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#15]
I want to be able to identify an element in a component file, and not have to load an action against it.
I want to be able to select that element and add an action against it in the step definition - if possible. This would allow for much better reuse - and less guessing of future testing requirements of that element

**Comment by phenomnomnominal** [comment]
This is totally the opposite of what we want, and in fact _prevents_ reuse. Defining your actions within the step definition makes that test inherently fragile - if your page changes, you would then have to modify your step definitions, potentially in multiple places. You really want to just change the page components implementation of that action. Ideally your actions should be written so that your step definitions are built up from generic actions, that are named so that they still make sense regardless of the exact interactions that made up the action. The step definitions shouldn't have any mention of buttons or clicking or entering text or anything like that. 

As for guessing future testing requirements, you shouldn't need to do that either, just add the action to the component when you are testing that action.
