### ISSUE TITLE
Multi instances: non-debug mode

### ISSUE THREAD

**Issue by jonoelkin** [TradeMe/tractor#95]
I want to be able to spin up Tractor across multiple instances using this...

```
capabilities: {
'browserName': 'chrome',
shardTestFiles: true,
maxInstances: 1
},
```

Problem is, 
when we run the tests on multiple instances, it is running it feature by feature. This means they are being run in the 'debug mode' Varun created. This is bad as it means tests hang, instead of failing and then moving on. I want to be able to run the entire tractor suite on multiple instances without debug mode being used.

**Comment by Galileo1** [comment]
@jonoelkin optional debug mode has been added. The only thing that is left is - to be able to choose multiple instances of the chrome instances from tractor. Even though this is no a good idea of having is locally inbuilt in the tractor and running it on everyone's local machine we will still keep it open for investigation. The reason I am saying this is because I have a dev branch which has already implemented this but I can see consistent results every time. But we will keep this issue open for investigating that part for now.

**Comment by phenomnomnominal** [comment]
https://github.com/phenomnomnominal/tractor-plugin-cucumber/commit/e200d4d4362fdcb1286b98b13bea084796cd0c40
